# Generated by Django 5.1.2 on 2024-12-10 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dimensao', models.CharField(choices=[('Organização Didático-Pedagógica', 'Organização Didático-Pedagógica'), ('Corpo Docente e Tutorial', 'Corpo Docente e Tutorial'), ('Infraestrutura', 'Infraestrutura')], max_length=50)),
                ('mensagem_aviso', models.TextField(blank=True)),
                ('tabela_conceitos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSA', models.BooleanField(default=False)),
                ('nivel_suposto', models.IntegerField(blank=True, null=True)),
                ('documento_tinymce', models.TextField(blank=True, null=True)),
                ('em_edicao', models.BooleanField(default=False)),
                ('edicao_inicio', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('indicador_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.indicadorinfo')),
                ('usuario_editando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_em_edicao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='indicadores/relatorios/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_pdfs', to='indicadores.indicadorman')),
                ('usuario_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
