# Generated by Django 5.1.2 on 2024-10-30 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dimensao', models.CharField(choices=[('Organização Didático-Pedagógica', 'Organização Didático-Pedagógica'), ('Corpo Docente e Tutorial', 'Corpo Docente e Tutorial'), ('Infraestrutura', 'Infraestrutura')], max_length=50)),
                ('mensagem_aviso', models.TextField(blank=True)),
                ('tabela_conceitos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSA', models.BooleanField(default=False)),
                ('nivel_suposto', models.IntegerField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('conteudo', models.FileField(blank=True, null=True, upload_to='indicadores/relatorios/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('indicador_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.indicadorinfo')),
                ('usuario_relatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
    ]
