# Generated by Django 5.1.2 on 2024-10-30 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('inscricao', models.TextField(blank=True)),
                ('detalhes', models.TextField(blank=True)),
                ('informacoes_complementares', models.TextField(blank=True)),
                ('capa', models.FileField(blank=True, null=True, upload_to='cursos/capas/')),
                ('privilegios', models.BooleanField(default=False)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_criados', to='usuarios.usuario')),
                ('relatores', models.ManyToManyField(blank=True, related_name='cursos', to='usuarios.usuario')),
            ],
        ),
    ]
