# Generated by Django 5.1.2 on 2024-12-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cursos_acesso',
            field=models.ManyToManyField(blank=True, related_name='visitantes', to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
