# Generated by Django 5.1.2 on 2024-12-10 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('indicadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('acao', models.PositiveIntegerField(choices=[(1, 'Cadastro de Relator'), (2, 'Edição de Relator'), (3, 'Cadastro de Visitante'), (4, 'Edição de Visitante'), (5, 'Criação de Curso'), (6, 'Edição de Curso'), (7, 'Edição de Informações Complementares'), (8, 'Envio de Capa'), (9, 'Substituição de Capa'), (10, 'Deleção de Capa'), (11, 'Postagem de Mensagem'), (12, 'Envio de Relatório'), (13, 'Substituição de Relatório'), (14, 'Deleção de Relatório'), (15, 'Edição de Conceito'), (16, 'Aplicação NSA'), (17, 'Desapliação do NSA'), (18, 'Adição de Acesso de Relator ao Curso'), (19, 'Remoção de Acesso ao Curso'), (20, 'Adição de Acesso a Visitante ao Curso'), (21, 'Remoção de Acesso de Visitante ao Curso'), (22, 'Edição mensagem'), (23, 'Deleção mensagem'), (24, 'Deleção visitante'), (25, 'Ceder criação'), (25, 'Delete de Curso')])),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('indicadorMan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicadores.indicadorman')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_visitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
